---
# common configuration
spring.kafka.bootstrap-servers: localhost:9092

logging.level:
  root: WARN
  com.gigaspaces.connector: DEBUG

---
# configuration for learning mode
spring.profiles: learning
spring.kafka.consumer-group: DIH-learning

metadata-provider:
  method: based-on-data
  parser: AdabasSoftwareAG
  topics: [LFPM_TNUOT_HAYOM_Schema,LFPM_TNUOT_HAYOM_PMOL-TNUOT_Schema]
  types-mapping:
    use-string-for-unlisted-types: true
    map:
      - source-type: "integer"
        dih-type: Integer
      - source_type: "string"
        dih-type: String
---
# configuration for connector mode
spring.profiles: connector
spring.kafka.consumer-group: DIH

space.name: demo