config:
  zookeeper:
    address: 127.0.X.X
    port: 2181
    connectionStr: 127.0.X.X:2181
    path: /publisher/adabas
  kafka:
    topic: $tableName$
    schemaTopic: $tableName$_Schema
    bootstrapAddress: 127.0.X.X:9092
    numPartitions: 1
    replicationFactor: 2
  retryTimeOut: 10000
  schemasPath: /tmp/schemas/2345678987654323456789876543456789765456787654567898765456787654

mq:
  hostname: h
  channel: c
  qManager: q
  queueName: qn
  sslChipherSuite: s
  port: 2222
  maxEvents: 1111
  testMode: False

test:
  path: /Users/yoramweinreb/work/bankleumi/kafka/adabasMessages.xml

server:
  port: 8071

management:
  server:
    port: 8071
  metrics:
    export:
      influx:
        enabled: false
      statsd:
        enabled: false
        flavor: telegraf
        port: 8125
  endpoints:
    web:
      port: 8071
      expose: "*"

logging:
  level:
    org.springframework: INFO
    com.gs.leumi: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: /dbagigalogs/Adabas/adabasPublisher.log
