#!/usr/bin/expect -f

set timeout -1

cd /dbagiga/gs-odsx
spawn ./odsx.py
# Servers
expect "Enter your option"
send -- "2\r"
# Influxdb
expect "Enter your option"
send -- "5\r"
# Remove
expect "Enter your option"
send -- "5\r"
# "Are you sure want to remove Influxdb servers"
expect "Are you sure want to remove Influxdb servers"
send -- "y\r"

# Exit
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"

expect eof
