#!/bin/bash

space_servers=$(sed -n '/space/,/dataIntegration/{//!p}' /dbagigashare/current/odsx/host.yaml|wc -l)
gsc_per_space_server=$(grep app.space.gsc.count /dbagigashare/current/odsx/app.config | awk -F= '{print $2}')
expected_containers=$(( $space_servers * $gsc_per_space_server ))
containers=$(/dbagiga/gigaspaces-smart-ods/bin/gs.sh --server=mng1 container list|grep "Containers"|awk '{print $NF}')
	echo containers=$containers
while (( $containers < $expected_containers )); do
	containers=$(/dbagiga/gigaspaces-smart-ods/bin/gs.sh --server=mng1 container list|grep "Containers"|awk '{print $NF}')
	echo containers=$containers
done
echo containers=$containers
auto_tsdeploy
