#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers di remove
# Are you sure want to remove DI servers
expect "Are you sure want to remove DI servers"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
