#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers manager upgrade
# Upgrade all managers
expect "for exit"
sleep 1
send -- "\n"
# Verify
expect "Are you sure want to continue manager gs"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
