#!/usr/bin/expect -f

cd /dbagiga/gs-odsx
set timeout -1
set force_conservative 1
spawn ./odsx.py dataengine gilboaupdater update install-deploy
expect "Are you sure want to proceed"
sleep .5
send -- "\n"

expect eof
