#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py tieredstorage deploy
# sure
expect "Are you sure want to proceed"
sleep 1
send -- "y"
sleep 1
send -- "\r"

expect eof
