#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers influxdb install
# directory
expect "Enter data directory Influxdb server"
sleep 1
send -- "\n"
# Influxdb
expect "Are you sure want to install Influxdb servers"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
