#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py monitors alerts services kapacitor start
expect "Are you sure want to start Kapacitor"
sleep .5
send -- "y"
sleep .5
send -- "\n"

expect eof
