#!/usr/bin/expect -f

cd /dbagiga/gs-odsx
set timeout -1
set force_conservative 1
spawn ./odsx.py dataengine oracle-feeder install-deploy
expect "to deploy all feeder"
sleep .5
send -- "\n"
expect "Are you sure want to proceed with all feeders"
sleep .5
send -- "y"
sleep .5
send -- "\n"

expect eof
