#!/usr/bin/expect -f

set timeout -1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers di start
# Servers
# Press [Enter] Start current configuration.
# Press [99] For exit.:
expect "For exit"
send -- "\r"
# Are you sure want to start kafka service
expect "Are you sure want to start kafka service"
send -- "\r"

expect eof
