#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers influxdb remove
expect "Are you sure want to remove Influxdb servers"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
