#!/usr/bin/expect -f

cd /dbagiga/gs-odsx
set timeout -1
set force_conservative 1
spawn ./odsx.py dataengine mssql-feeder install-deploy
expect "Are you sure want to proceed"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
