#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers di start
# Start
expect "For exit"
sleep 1
send -- "\n"
# Are you sure want to start kafka service
expect "Are you sure want to start kafka service"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
