#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py object objectmanagement registration registertypeinbatch
expect "Do you want to continue object registration with above inputs"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
