#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers grafana remove
# User
expect "Enter user to connect to Grafana"
sleep 1
send -- "\n"
# Sure
expect "Are you sure want to remove Grafana servers"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
