#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers space start
# All servers
expect "for exit"
sleep 1
send -- "\r"
# Verify
expect "Are you sure want to start all servers"
sleep 1
send -- "y"
sleep 1
send -- "\r"

expect eof
