#!/usr/bin/expect -f

cd /dbagiga/gs-odsx
set timeout -1
set force_conservative 1
spawn ./odsx.py dataengine gilboaupdater fullload install-deploy
expect "to deploy all feeder"
sleep .5
send -- "\n"
expect "Are you sure want to proceed"
sleep .5
send -- "\n"

expect eof
