#!/bin/bash

_LOG=/var/log/auto_odsx.log
_FULL_LOG=/dbagigalogs/auto_odsx_full.log
echo -e "$(date) ===Starting bllspace space reinstall===" | tee -a $_LOG $_FULL_LOG

cd /dbagiga/utils/auto_odsx
echo -e "$(date) Stopping ODS Space servers" | tee -a $_LOG $_FULL_LOG
./auto_spacestop 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Removing ODS Space servers" | tee -a $_LOG $_FULL_LOG
./auto_spaceremove 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Installing ODS Space servers" | tee -a $_LOG $_FULL_LOG
./auto_spaceinstall 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Stopping ODS Manager servers" | tee -a $_LOG $_FULL_LOG
./auto_managerstop 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Removing ODS Manager servers" | tee -a $_LOG $_FULL_LOG
./auto_managerremove 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Installing ODS Manager servers" | tee -a $_LOG $_FULL_LOG
./auto_managerinstall 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Starting ODS Manager servers" | tee -a $_LOG $_FULL_LOG
./auto_managerstart 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Starting ODS Space servers" | tee -a $_LOG $_FULL_LOG
./auto_spacestart 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Deploy TS after all bllspace GSC's are up" | tee -a $_LOG $_FULL_LOG
./auto_tsdeploy_check 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Load benchmark data into bllspace" | tee -a $_LOG $_FULL_LOG
./auto_benchmark 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Deploy db2-feeders" | tee -a $_LOG $_FULL_LOG
./auto_db2feederdeploy 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Deploy mssql-feeders" | tee -a $_LOG $_FULL_LOG
./auto_mssqlfeederdeploy 2>&1 | tee -a $_FULL_LOG

echo -e "$(date) ===Finished bllspace space reinstall===" | tee -a $_LOG $_FULL_LOG
