#!/usr/bin/expect -f

set timeout -1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers di install
# Are you sure want to install DI servers
expect "Are you sure want to install DI servers"
send -- "y\r"

expect eof
