#!/usr/bin/expect -f

cd /dbagiga/gs-odsx
set timeout -1
set force_conservative 1
spawn ./odsx.py dataengine gilboaupdater update remove-undeploy
expect "Proceeding with manager host"
sleep .5
send -- "\n"
expect "For exist"
sleep .5
send -- "\n"
expect "Enter drain mode"
sleep .5
send -- "\n"
expect "Enter drain mode timeout"
sleep .5
send -- "\n"
expect "Do you want to remove gsc"
sleep .5
send -- "\n"

expect eof
