#!/usr/bin/expect -f

set timeout -1

cd /dbagiga/gs-odsx
spawn ./odsx.py 

expect "Enter your option"
send -- "3\r"
expect "Enter your option"
send -- "4\r"
expect "Enter your option"
send -- "6\r"

#Exit
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"

expect eof
