#!/bin/bash
source ~/.bashrc
_LOG=/var/log/auto_odsx.log
_FULL_LOG=/dbagigalogs/auto_odsx_full.log
echo -e "$(date) ===Starting space refresh===" | tee -a $_LOG $_FULL_LOG

echo -e "$(date) Stopping ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spacestop 2>&1 | tee -a $_FULL_LOG

if [[ "${ENV_NAME}" != "TAUG" ]] ; then
  echo -e "$(date) Stopping ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerstop 2>&1 | tee -a $_FULL_LOG
fi

echo -e "$(date) Cleaning ODS Manager and Space directories" | tee -a $_LOG $_FULL_LOG
auto_cleandirsspaces 2>&1 | tee -a $_FULL_LOG
auto_cleandirsmanagers 2>&1 | tee -a $_FULL_LOG

if [[ "${ENV_NAME}" != "TAUG" ]] ; then
  echo -e "$(date) Starting ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerstart 2>&1 | tee -a $_FULL_LOG
  auto_managerlist 2>&1 | tee -a $_FULL_LOG
fi

echo -e "$(date) Starting ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spacestart 2>&1 | tee -a $_FULL_LOG
auto_spacelist 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Deploy TS after all space server GSC's are up" | tee -a $_LOG $_FULL_LOG
auto_tsdeploy_check 2>&1 | tee -a $_FULL_LOG

echo -e "$(date) Disable object-management.service" | tee -a $_LOG $_FULL_LOG
auto_objectdisable
echo -e "$(date) Enable object-management.service" | tee -a $_LOG $_FULL_LOG
auto_objectenable
# Yuval
exit
echo -e "$(date) Wait 10s to do object registration." | tee -a $_LOG $_FULL_LOG
sleep 10
auto_objectregistration | tee -a $_FULL_LOG

#echo -e "$(date) Load benchmark data into space" | tee -a $_LOG $_FULL_LOG
#auto_benchmark 2>&1 | tee -a $_FULL_LOG

if [[ "${ENV_NAME}" == "TAUG" ]] ; then
  echo -e "$(date) Deploying all feeders." | tee -a $_LOG $_FULL_LOG
  auto-tau-oracle-feeders.sh -a  | tee -a $_FULL_LOG
  echo -e "$(date) Loading all tables with 10 records." | tee -a $_LOG $_FULL_LOG
  auto-tau-oracle-feeders.sh -startall10 | tee -a $_FULL_LOG
fi

echo -e "$(date) ===Finished space refresh===" | tee -a $_LOG $_FULL_LOG
