#!/usr/bin/expect -f

set timeout -1

cd /dbagiga/gs-odsx
spawn ./odsx.py
# Servers
expect "Enter your option"
send -- "2\r"
# Manager
expect "Enter your option"
send -- "1\r"
# Stop
expect "Enter your option"
send -- "3\r"
# "Press [Enter] to stop all."
expect "for exit"
send -- "\r"
# Sure
expect "Are you sure want to stop all servers"
send -- "y\r"

# Exit
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"
expect "Enter your option"
send -- "99\r"

expect eof
