#!/bin/bash

cd /dbagiga/utils/auto_odsx
auto_spacestop
auto_spaceremove
read -sn1 -p "Press to install space"
auto_spaceinstall
auto_managerstop
auto_managerremove
read -sn1 -p "Press to install manager"
auto_managerinstall
auto_managerstart
auto_spacestart
