#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers northbound remove all
# proceed
expect "Are you sure want to proceed for uninstallation"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
