#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py object objectmanagement registration addindexinbatch
expect "Do you want to continue object registration with above inputs"
sleep .5
send -- "y"
sleep .5
send -- "\n"

expect eof
