#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py object objectmanagement registration list
expect "or exit"
sleep 0.5
send -- "9"
sleep 0.5
send -- "9"
sleep 0.5
send -- "\r"

expect eof
