#!/bin/bash

_LOG=/var/log/auto_odsx.log
_FULL_LOG=/dbagigalogs/auto_odsx_full.log
_WAIT=120

echo -e "$(date) ===Starting DIH space reinstall===" | tee -a $_LOG $_FULL_LOG

cd /dbagiga/utils/auto_odsx
echo -e "$(date) Stopping ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spacestop 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Removing ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spaceremove 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Installing ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spaceinstall 2>&1 | tee -a $_FULL_LOG

if [[ "${ENV_NAME}" != "TAUG" ]] ; then
  echo -e "$(date) Stopping ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerstop 2>&1 | tee -a $_FULL_LOG
  echo -e "$(date) Removing ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerremove 2>&1 | tee -a $_FULL_LOG
  echo -e "$(date) Installing ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerinstall 2>&1 | tee -a $_FULL_LOG
  echo -e "$(date) Starting ODS Manager servers" | tee -a $_LOG $_FULL_LOG
  auto_managerstart 2>&1 | tee -a $_FULL_LOG
fi

#[[ "${ENV_NAME}" == "TAUG" ]] && runhosts.sh -m 'sed -i "/GS_OPTIONS_EXT=/ s/\"$/ -Dcom.gs.expose.internal.api=true\"/" /giga/gigaspaces-smart-ods/bin/setenv-overrides.sh'

echo -e "$(date) Starting ODS Space servers" | tee -a $_LOG $_FULL_LOG
auto_spacestart 2>&1 | tee -a $_FULL_LOG
echo -e "$(date) Deploy space in-memory after all space GSC's are up" | tee -a $_LOG $_FULL_LOG
#auto_tsdeploy_check 2>&1 | tee -a $_FULL_LOG
auto_inmemorydeploy_check
echo -e "$(date) Disable object-management.service" | tee -a $_LOG $_FULL_LOG
auto_objectdisable
echo -e "$(date) Enable object-management.service" | tee -a $_LOG $_FULL_LOG
auto_objectenable
echo -e "$(date) Wait 10s before doing Register Type In Batch." | tee -a $_LOG $_FULL_LOG
sleep 10
auto_objectregistration
echo -e "$(date) Starting Object Index Registration." | tee -a $_LOG $_FULL_LOG
auto_objectindexregistration

echo -e "$(date) Resetting oracleFeeder.db." | tee -a $_LOG $_FULL_LOG
auto_oraclefeederreset
echo -e "$(date) Starting to deploy ORACLE feeders." | tee -a $_LOG $_FULL_LOG
auto_oraclefeederdeploy

echo -e "$(date) Starting ORACLE feeders for ${_WAIT} seconds then stopping." | tee -a $_LOG $_FULL_LOG
[[ "${ENV_NAME=}" == "TAUP" ]] && { auto_oraclefeederstart ; sleep ${_WAIT} ; auto_oraclefeederstop ; }

# Yuval
exit

#echo -e "$(date) Load benchmark data into space" | tee -a $_LOG $_FULL_LOG
#auto_benchmark 2>&1 | tee -a $_FULL_LOG

if [[ "${ENV_NAME}" == "TAUG" ]] ; then
  auto-tau-oracle-feeders.sh -a
  auto-tau-oracle-feeders.sh -startall10
fi

echo -e "$(date) ===Finished DIH space reinstall===" | tee -a $_LOG $_FULL_LOG
