#!/usr/bin/expect -f

set timeout -1
set force_conservative 1
cd /dbagiga/gs-odsx
spawn ./odsx.py utilities cleandirectories managerservers
expect "Are you sure want to delete above directories"
sleep 1
send -- "\r"

expect eof
