#!/usr/bin/expect -f

set timeout -1
set force_conservative 1

cd /dbagiga/gs-odsx
spawn ./odsx.py servers northbound install all
# Confirm
expect "Are you sure want to proceed for installation"
sleep 1
send -- "y"
sleep 1
send -- "\n"

expect eof
