{
 "title": "Infrastructure",
 "description": "Infrastructure",
 "tags": [ "Master" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"process_cpu_used-percent\" WITH KEY  = \"host\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 0 },
   "options": {
    "content": "   <a href=\"/d/tJWLBOR7z/main-dashboard?orgId=1&refresh=5s&kiosk\">\n         <div>\n         <img alt=\"Customer Spaceboard\" src=\"/public/img/Customer.png\"\n         width=150\">\n         <span style=\"font-size:150%; font-weight:bold ;color:darkblue; padding-left:10px; font-style:italic\"> SpaceBoard > Infrastructure </span>\n         </div>\n      </a>\n   \n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "title": "Host CPU %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_cpu_used-percent",
     "query": "SELECT last(\"value\") FROM \"os_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Host Memory  %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_memory_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "GSCs CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Container pid: $tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_used-percent",
     "query": "SELECT mean(\"value\") FROM \"process_cpu_used-percent\" WHERE (\"process_name\" = 'gsc' AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "GSCs memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Container pid: $tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-percent",
     "query": "SELECT mean(\"value\") FROM \"jvm_memory_heap_used-percent\" WHERE (\"process_name\" = 'gsc' AND \"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "gsc" }
     ]
    }
   ]
  },
  {
   "title": "Manager Processes",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"up time\" FROM \"jvm_uptime\" WHERE (\"host\" =~ /^$Host$/ AND \"process_name\" = 'manager') AND $timeFilter GROUP BY time($__interval), \"pid\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "manager" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "up time" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "manager" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "jvm_uptime",
     "query": "SELECT last(\"value\") AS \"CPU\" FROM \"process_cpu_used-percent\" WHERE (\"host\" =~ /^$Host$/) AND $timeFilter GROUP BY time($__interval), \"pid\", \"process_name\" fill(null) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$Host$/" },
      { "condition": "AND", "key": "process_name", "operator": "=", "value": "manager" }
     ]
    }
   ]
  },
  {
   "title": "Managers memory",
   "type": "graph",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Manager pid:  $tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "manager" }
     ]
    }
   ]
  },
  {
   "title": "Managers cpu",
   "type": "graph",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Manager pid:  $tag_pid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "process_name", "operator": "=", "value": "manager" }
     ]
    }
   ]
  }
 ]
}