params:
  cockpit:
    db_home: 
    db_name: 
  dr:
    endpoints:
      pivot: 
      rest: 
    variables:
      pivot: PIVOT_DR
      rest: ENDPOINT_DR
  prd:
    endpoints:
      pivot: 
      rest: 
    variables:
      pivot: PIVOT_PRD
      rest: ENDPOINT_PRD
types:
  1: 'Validate'
  2: 'Deploy MS'
  3: 'Deploy Feeder'
  4: 'Feeder Job'
  5: 'IIDR Job'
  6: 'Adabas Consumer Job'
  7: 'MSSQL Job'
  