params:
  cockpit:
    db_home: /tmp/sqlite
    db_name: cockpit.db
  dr:
    endpoints:
      pivot: 2.2.2.2
      rest: null
    variables:
      pivot: PIVOT_DR
      rest: ENDPOINT_DR
  prd:
    endpoints:
      pivot: 1.1.1.1
      rest: null
    variables:
      pivot: PIVOT_PRD
      rest: ENDPOINT_PRD
