---
#
# the menu file basically consists of two types of elements (set under 'type' key):
# menu:    only shows a list of chioces
# command: executes some script/command
#
# every menu/sub-menu element requires an index key to represent its place in the yaml structure
#
# the command element requires the same as the menu element but also has specific keys
# to allow the execution of commands/procedures
# exec-type: distinguishes between execution types
#            module :: for python modules or functions imports
#            script :: shell/python scripts
# exec:      the name of the script/module/function to execute
#

id: 'Main'
type: 'menu'
description: ''
1:
    id: 'Tasks'
    type: 'menu'
    description: 'Task is a collection of one or more jobs'
    1: 
        id: 'Tasks Catalog'
        type: 'menu'
        description: 'Catalog of registered tasks'
        1:
            id: 'List Tasks'
            type: 'command'
            exec-type: 'script'
            exec: 'list_tasks.py'
            description: 'List registered tasks'
        2:
            id: 'Show Tasks'
            type: 'command'
            exec-type: 'script'
            exec: 'show_task.py'
            description: 'Show selected task information'

    2:
        id: 'Create New Task'
        type: 'command'
        exec-type: 'script'
        exec: 'create_new_task.py'
        description: 'Create a new task'

    3:
        id: 'Edit Tasks'
        type: 'menu'
        description: 'Edit a registered task'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'The task name'
        2:
            id: 'Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'The policy associated with the task'
        3:
            id: 'Activate'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Set a task as active'
        4:
            id: 'Deactivate'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Set a task as inactive'
        5:
            id: 'Add job'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Associate a job with a task'
        6:
            id: 'Remove job'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Disassociate a job from a task'
        7:
            id: 'Show metadata'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Show task metadata'
    4:
        id: 'Delete Tasks'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'Delete/Deregister a task'
2:
    id: 'Jobs'
    type: 'menu'
    description: 'A job is the most basic (atomic) component associated with a task'
    1: 
        id: 'Jobs Catalog'
        type: 'menu'
        description: 'The catalog of registered jobs'
        1:
            id: 'List Jobs'
            type: 'command'
            exec-type: 'script'
            exec: 'list_jobs.py'
            description: 'List registered jobs'
        2:
            id: 'Show Jobs'
            type: 'command'
            exec-type: 'script'
            exec: 'show_job.py'
            description: 'Show selected job information'
        3:
            id: 'Test Job'
            type: 'command'
            exec-type: 'script'
            exec: 'test_job.py'
            description: 'Try/Test a selected job'
    2:
        id: 'Create New Job'
        type: 'menu'
        description: 'Create a new job from list of job types'
        1:
            id: 'Entries Counter'
            type: 'command'
            exec-type: 'script'
            exec: 'create_counter_job.py'
            description: 'Get entry count for an object in space'
        2:
            id: 'Start Feeder'
            type: 'command'
            exec-type: 'script'
            exec: 'feeder_start.py'
            description: 'Start a feeder'
        3:
            id: 'Stop Feeder'
            type: 'command'
            exec-type: 'script'
            exec: 'feeder_stop_.py'
            description: 'Stop a feeder'
        4:
            id: 'Deploy Feeder'
            type: 'command'
            exec-type: 'script'
            exec: 'feeder_deploy.py'
            description: 'Deploy a feeder'
    3:
        id: 'Edit Job'
        type: 'menu'
        description: 'Select a job and change its attributes'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        2:
            id: 'Command'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        3:
            id: 'Destination'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        4:
            id: 'Metadata'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    4:
        id: 'Delete job'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'Delete a job if not associated with a task'
3:
    id: 'Policies'
    type: 'menu'
    description: 'A policy defines when and how task(s) are executed'
    1: 
        id: 'Policies Catalog'
        type: 'menu'
        description: 'The catalog of registered jobs'
        1:
            id: 'List Policies'
            type: 'command'
            exec-type: 'script'
            exec: 'list_policies.py'
            description: 'List registered policies'
        2:
            id: 'Show Policies'
            type: 'command'
            exec-type: 'script'
            exec: 'show_policy.py'
            description: 'Show selected job information'
    2:
        id: 'Create New Policy'
        type: 'command'
        exec-type: 'script'
        exec: 'create_new_policy.py'
        description: 'Create a new policy for existing tasks'
    3:
        id: 'Edit Policies'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        2:
            id: 'Schedule'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        3:
            id: 'Retry'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        4:
            id: 'Activate Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        5:
            id: 'Deactivate Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    4:
        id: 'Delete Policy'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
4:
    id : 'Reporting'
    type: 'menu'
    description: 'Explore statistics of cockpit elements'
    1: 
        id: 'Task Execution'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'List Last 15'
            type: 'command'
            exec-type: ''
            exec: ''

            description: 'add description here'
        2:
            id: 'Show Executions'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    2:
        id: 'Task Cancellation'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
    3:
        id: 'Jobs Monitor'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
5:
    id: 'Settings/Status'
    type: 'menu'
    description: 'Display cockpit settings and status'
    1: 
        id: 'IP/Endpoint for PROD'   
        type: 'command'
        exec-type: 'script'
        exec: 'get_prd_params.py'
        description: 'Show/Setup network settings for PROD'
    2:
        id: 'IP/Endpoint for DR'
        type: 'command'
        exec-type: 'script'
        exec: 'get_dr_params.py'
        description: 'Show/Setup network settings for DR'
    3:
        id: 'Cockpit DB'
        type: 'command'
        exec-type: 'script'
        exec: 'db_info.py'
        description: 'Show database information'
...