---
#
# the menu file basically consists of two types of elements (set under 'type' key):
# menu:    only shows a list of chioces
# command: executes some routine/command
#
# the menu element: only requires adding an index under which it will reside in the yaml structure
#
# the command element: requires the same as menu element but also has specific keys
# to allow the execution of commands/procedures
# exec-type: distinguishes between types execution
#            module :: python modules or functions
#            script :: shell script
# exec:      the name of the script / module / function to execute
#

id: 'Main'
type: 'menu'
description: ''
1:
    id: 'Tasks'
    type: 'menu'
    description: 'Task is a collection of one or more jobs'
    1: 
        id: 'Tasks Catalog'
        type: 'menu'
        description: 'Catalog of registered tasks'
        1:
            id: 'List Tasks'
            type: 'command'
            exec-type: 'module'
            exec: 'list_tasks'
            description: 'List registered tasks'
        2:
            id: 'Show Tasks'
            type: 'command'
            exec-type: 'module'
            exec: 'show_task'
            description: 'Show selected task information'

    2:
        id: 'Create New Task'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'Register a new task'

    3:
        id: 'Edit Tasks'
        type: 'menu'
        description: 'Edit a registered task'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'The task name'
        2:
            id: 'Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'The policy associated with the task'
        3:
            id: 'Activate'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Set a task as active'
        4:
            id: 'Deactivate'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Set a task as inactive'
        5:
            id: 'Add job'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Associate a job with a task'
        6:
            id: 'Remove job'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Disassociate a job from a task'
        7:
            id: 'Show metadata'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Show task metadata'
    4:
        id: 'Delete Tasks'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'Delete/Deregister a task'
2:
    id: 'Jobs'
    type: 'menu'
    description: 'Job is the atomic component associated with a task'
    1: 
        id: 'Jobs Catalog'
        type: 'menu'
        description: 'Catalog of registered jobs'
        1:
            id: 'List Jobs'
            type: 'command'
            exec-type: 'script'
            exec: 'job_sample.sh'
            description: 'List registered jobs'
        2:
            id: 'Show Jobs'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'Show selected job information'
    2:
        id: 'Create New Job'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'Validate'
            type: 'command'
            exec-type: 'script'
            exec: 'validation_generator.py'
            description: 'Get entries count for a specific object type'
        2:
            id: 'Start Feeder'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        3:
            id: 'Pause Feeder'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        4:
            id: 'Deploy Feeder'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    3:
        id: 'Edit Job'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        2:
            id: 'command'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        3:
            id: 'Destination'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        4:
            id: 'Metadata'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    4:
        id: 'Delete job'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
3:
    id: 'Policies'
    type: 'menu'
    description: 'this is a description for policies'
    1: 
        id: 'Policies Catalog'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'List Policies'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        2:
            id: 'Show Policies'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    2:
        id: 'Create new policy'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
    3:
        id: 'Edit Policies'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'Name'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        2:
            id: 'Schedule'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        3:
            id: 'Retry'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        4:
            id: 'Activate Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
        5:
            id: 'Deactivate Policy'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    4:
        id: 'Delete Policy'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
4:
    id : 'Reporting'
    type: 'menu'
    description: 'this is a description for reporting'
    1: 
        id: 'Task Execution'
        type: 'menu'
        description: 'add description here'
        1:
            id: 'List last 15'
            type: 'command'
            exec-type: ''
            exec: ''

            description: 'add description here'
        2:
            id: 'Show executions'
            type: 'command'
            exec-type: ''
            exec: ''
            description: 'add description here'
    2:
        id: 'Task Cancellation'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
    3:
        id: 'Jobs Monitor'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
5:
    id: 'Settings'
    type: 'menu'
    description: 'this is a description for settings'
    1: 
        id: 'IP/Endpoint for PROD'   
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
    2:
        id: 'IP/Endpoint for DR'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
    3:
        id: 'Cockpit DB'
        type: 'command'
        exec-type: ''
        exec: ''
        description: 'add description here'
...