package com.gs.csm.data;


import com.gigaspaces.annotation.pojo.SpaceId;

import java.io.Serializable;
import java.sql.Date;


/**
 * This class was auto-generated by GigaSpaces
 */


public class IBMStock implements Serializable {
    private Date Date;
    private String Id;
    private Double Open;
    private Double High;
    private Double Low;
    private Double  Close;
    private Double  Volume;
    private Double  OpenInt;

    public IBMStock() {
    }

    @SpaceId(autoGenerate = true)
    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    public java.sql.Date getDate() {
        return Date;
    }

    public void setDate(java.sql.Date date) {
        Date = date;
    }

    public Double getOpen() {
        return Open;
    }

    public void setOpen(Double open) {
        Open = open;
    }

    public Double getHigh() {
        return High;
    }

    public void setHigh(Double high) {
        High = high;
    }

    public Double getLow() {
        return Low;
    }

    public void setLow(Double low) {
        Low = low;
    }

    public Double getClose() {
        return Close;
    }

    public void setClose(Double close) {
        Close = close;
    }

    public Double getVolume() {
        return Volume;
    }

    public void setVolume(Double volume) {
        Volume = volume;
    }

    public Double getOpenInt() {
        return OpenInt;
    }

    public void setOpenInt(Double openInt) {
        OpenInt = openInt;
    }
}

