#!/usr/bin/env bash

# Comments:
# /opt/homebrew/bin/bash - new bash v5
# cd ; tail -100f HTTP_CODE | grep "[13456][0-9][0-9]\|ID="

# Check requirements

function requirements() {
[[ $# -eq 0 || $1 == "-h" ]] && usage
python3 --version >/dev/null 2>&1 || { echo -e "\nInstall python3\n" ; exit 1 ; }
[[ ! "$(basename $(pwd))" == "erag" ]] && { echo -e "\nRun script inside folder named \"erag\"\n" ; exit 1 ; }
if [[ "$(echo "${@}" | grep -o -- '-file')" != "-file" && ! -s accuracy.tsv ]] ; then
  echo ; [[ "$(echo "${@}" | grep -o -- '-file')" != "-file" ]] && echo -e "The \"-file\" argument is missing."
  [[ ! -s accuracy.tsv ]] && echo -e "The file \"accuracy.tsv\" is missing or empty."
  echo ; exit 1
fi
}

# ENVIRONMENT

function do_env() {
# goldenset API
# FastAPI='https://tenant-goldenset.erag-c1.gigaspaces.net/api/data-lab'
# eRAG_experimental_app='https://tenant-goldenset.erag-c1.gigaspaces.net/api/erag-backend'
# tempo2 API
# https://tenant-tempo2.erag-c1.gigaspaces.net/api/data-lab/docs
# https://tenant-tempo2.erag-c1.gigaspaces.net/api/erag-backend/docs
FastAPI=""
eRAG_experimental_app=""
_OUTPUT=""
_ACCURACY_FILE="accuracy.tsv"
_CURL_RESPONSE="/tmp/erag_curl_response"
declare -g -A _EXIT_CODE
declare -g -A _HTTP_CODE
# goldenset token - Authorization: Token -WiA1-MmPjMG_BHxyo$8Ndze5uz4@CQ1BgRbcVtPMo
# tempo2 token - Authorization: Token 7K@htaemdlptf7R_$@1VjZ8USukKj@hwyuikAUFQE5
_TOK='Authorization: Token 7K@htaemdlptf7R_$@1VjZ8USukKj@hwyuikAUFQE5'
_APPLICATIONID=""
#_USERID="24050ffc-9cf9-4ddc-9dec-35be40f164c0"      # goto env webpage -> f1 -> login -> Network:Fetch/XHR:Name(Headers) user-id
_USERID=b1cd3e11-f689-435e-939a-8eb83491b8e6
_CORRELATION_UID=""
_TOPICID=""
_TOPIC_IDS=""                     # Contains all topicids when specifying -getids argument 
_MSG_BODY=""
_MSG_BODY_ID=""
_SQL=""                           # New SQL statement
_SQL_SED=""                       # New SQL statement - escaping double quotes are escaped: \"
_SQL_ORIG=""                      # Original SQL statement
_SQL_ORIG_SED=""                  # Original SQL statement - double quotes are escaped: \"
_MSG_DETAILS=""
_NL_RESULT=""                     # Get Natural Language answer to SQL
_NL_RESULT_ORIG=""                # Get Natural Language answer to SQL_ORIG
_NL_RESULT2=""                     # Get Natural Language answer to SQL
_NLP_RESULT2=""
_FIRST_ID=1
_LAST_ID=50
LC_ALL=US date '+%Y-%m-%d %H:%M:%S' >> HTTP_CODE        # Hold http codes for current run
LC_ALL=US date '+%Y-%m-%d %H:%M:%S' > GET_NL_RESULT
# Variables for report
_SERIAL=""                        # Question ID
_QUESTION=""                      # Question asked - double quotes are escaped: \"
_RESULT=""                        # Current Query result
_RESULT_ORIG=""                   # Confirmed Query result
_SLEEP=""
_ERR_LOG=/tmp/erag-error.log
_ERR_LOG_TMP=/tmp/erag-error-tmp.log
}

check_python_venv() {

# Define the virtual environment path
VENV_PATH="myvenv"
# Step 1: Check if the virtual environment exists
if [ ! -d "$VENV_PATH" ]; then
    #echo "Virtual environment not found. Creating one..."
    python3 -m venv "$VENV_PATH" || { echo "Failed to create virtual environment"; exit 1; }
fi
# Step 2: Activate the virtual environment
source "$VENV_PATH/bin/activate" || { echo "Failed to activate virtual environment"; exit 1; }
# Step 3: Check if beautifulsoup4 is installed
if ! pip show beautifulsoup4 > /dev/null 2>&1; then
    #echo "BeautifulSoup4 is not installed. Installing it now..."
    pip install beautifulsoup4 || { echo "Failed to install BeautifulSoup4"; exit 1; }
fi
}

# FUNCTIONS

# GET 1 - Get application id - eRAG experimental app/Get All Applications
##  'https://tenant-goldenset.erag-c1.gigaspaces.net/api/erag-backend/v1/applications' \
function get_applicationid() {

  _HTTP_CODE["${FUNCNAME[0]}"]=$( curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'GET' \
  "${eRAG_experimental_app}/v1/applications" \
  -H 'accept: application/json' \
  -H "${_TOK}")
  _APPLICATIONID="$( jq -e '.[].applicationId' < ${_CURL_RESPONSE} 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_applicationid " ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  echo "${_APPLICATIONID}" > debug/${my_id}_APPLICATIONID-$_OUTPUT   #debug

}

# GET 2 - Get topic ids - FastAPI/get all topics for this app for this user
function get_all_topicids() {

  get_applicationid                         # set _APPLICATIONID
  _TOPIC_IDS=$( curl -sX 'GET' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}" | jq '.[].id' )

}

# POST - Create topic - FastAPI/Create a new topic
function get_topicid() {

_TOPICID=$( curl -sX 'POST' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}" \
  -H 'Content-Type: application/json' \
  -d '{ "name": "Topic creation for testing." }' | jq '.id' )
  echo "${_TOPICID}" > debug/${my_id}_TOPICID-$_OUTPUT   #debug

}

# GET 3 - Get message body id - FastAPI/Submit a new question to the topic
# The _MSG_BODY_ID always is equal (e.g. 2990)
function post_message() {

  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'POST' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics/${_TOPICID}/messages" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "correlation-id: ${_CORRELATION_UID}" \
  -H "${_TOK}" \
  -H 'Content-Type: application/json' \
  -d '{
    "message": "'"${_QUESTION}"'",
    "historical_message_id": null
  }')

  _MSG_BODY=$(<${_CURL_RESPONSE})
  echo "${_MSG_BODY}" > debug/${my_id}_MSG_BODY-$_OUTPUT   #debug
  #_MSG_BODY_ID="$(echo "${_MSG_BODY}" | jq -e '.[] | select(.role == "assistant") | .id')"
  # jq -er '...' <<< "$myvar"                    # Using a here-string
  # jq -er '.name' < <(echo "$myvar")            # Using process substitution
  _MSG_BODY_ID="$( jq -e '.[] | select(.role == "assistant") | .id' <<< "${_MSG_BODY}" 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_topicid _MSG_BODY_ID" "$(<${_ERR_LOG_TMP})" ; } >> $_ERR_LOG
  echo "${_MSG_BODY_ID}" > debug/${my_id}_MSG_BODY_ID-$_OUTPUT   #debug

}

# GET 4 - Use message_id to get sql "Current SQL statement - generated" - FastAPI/Get message details
function get_message_details() {

  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'GET' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics/${_TOPICID}/messages/${_MSG_BODY_ID}" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "correlation-id: ${_CORRELATION_UID}" \
  -H "${_TOK}")
  _MSG_DETAILS=$(<${_CURL_RESPONSE})
  echo "${_MSG_DETAILS}" > debug/${my_id}_MSG_DETAILS-$_OUTPUT   #debug
  #_SQL=$(echo "${_MSG_DETAILS}" | jq -er '.sql')
  _SQL=$( jq -er '.sql' <<< "${_MSG_DETAILS}" 2> $_ERR_LOG_TMP )
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_message_details _SQL" ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  echo "${_SQL}" > debug/${my_id}_SQL-$_OUTPUT   #debug
  _SQL_SED=$(echo "${_SQL}" | sed 's/"/\\"/g')
  echo "${_SQL_SED}" > debug/${my_id}_SQL_SED-$_OUTPUT   #debug
  declare -p _HTTP_CODE >> HTTP_CODE

}

# Use sql/sql_orig to get "data" and "nl_result" - eRAG experimental app/Sql Nlp Query
# $1 - sql statement
# $2 - NL_RESULT_ORIG or NL_RESULT
function get_nl_result() {

  local run_sql="$(echo -n "${1}" | sed "s/'/'\\\''/g" | tr -d '\n\r')"
  local nl_result_type=$2                          # either NL_RESULT or NL_RESULT_ORIG
  #local run_sql="$(echo -n "${1}" | tr -d '\n\r')"
  echo "${run_sql}" > debug/${my_id}_${nl_result_type}_get_nl_result_run_sql-$_OUTPUT   #debug

  # Build the curl command in an array
  cat << EOF > debug/${my_id}_${nl_result_type}_get_nl_result_curl_cmd-$_OUTPUT
  curl -s -o "${_CURL_RESPONSE}" -w "%{http_code}" \\
  -X 'POST' '${eRAG_experimental_app}/v1/toucan-sql/sql-nlp-query' \\
  -H 'accept: application/json' \\
  -H 'correlation-id: ${_CORRELATION_UID}' \\
  -H 'user-id: ${_USERID}' \\
  -H '${_TOK}' \\
  -H 'Content-Type: application/json' \\
  -d '{
  "query": "${_QUESTION}",
  "sql": "${run_sql}",
  "model": "azure-openai-gpt4o-2024-08-06",
  "applicationId": ${_APPLICATIONID}
  }'
EOF

  _HTTP_CODE["${FUNCNAME[0]}"]=$(bash debug/${my_id}_${2}_get_nl_result_curl_cmd-$_OUTPUT)
  cat ${_CURL_RESPONSE} > debug/${my_id}_${2}_CURL_RESPONSE-$_OUTPUT   #debug
  cat ${_CURL_RESPONSE}                 # Return result to function caller

}

# Get npl query - eRAG experimental app/Nlp Query
function get_nl_result2() {

local outfile="debug/${my_id}_NL_RESULT_get_nl_result_curl_cmd-$_OUTPUT"
cat << EOF > $outfile
curl -s -o "${_CURL_RESPONSE}" -w "%{http_code}" \\
  -X 'POST' '${eRAG_experimental_app}/v1/toucan-sql/nlp-query' \\
  -H 'accept: application/json' \\
  -H 'correlation-id: ${_CORRELATION_UID}' \\
  -H 'user-id: ${_USERID}' \\
  -H '${_TOK}' \\
  -H 'Content-Type: application/json' \\
  -d '{
  "query": "${_QUESTION}",
  "queryEn": "",
  "queriesHistorical": [],
  "evidence": "",
  "model": "azure-openai-gpt4o-2024-08-06",
  "applicationId": ${_APPLICATIONID},
  "skipCacheSearch": true,
  "skipSchemaFiltering": true
  }'
EOF

  _HTTP_CODE["${FUNCNAME[0]}"]=$( bash $outfile )
  cat ${_CURL_RESPONSE} > debug/${my_id}_NL_RESULT_CURL_RESPONSE-$_OUTPUT   #debug
  cat ${_CURL_RESPONSE}                 # Return result to function caller

}

function delete_topic() {

curl -sX 'DELETE' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics/${_TOPICID}" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}"

}

function delete_all_topicids() {

  get_all_topicids
  [[ $( echo $_TOPIC_IDS | wc -w ) -eq 0 ]] && { echo -e "\nNo topics to delete.\n" ; exit ; }
  local id
  for id in $_TOPIC_IDS ; do
    _TOPICID=$id
    echo "Deleting topic ${id}"
    delete_topic
  done

}

function get_correlation_id() {

  _CORRELATION_UID=$(uuidgen)
  echo "${_CORRELATION_UID}" > debug/${my_id}_CORRELATION_UID-$_OUTPUT   #debug

}


###################################
# Compare original sql with new sql
# col1 = Serial
# col2 = Question
# col3 = Query
# Date, question ID, question, Confirmed query, Current query, comparison results (correct, not correct, inconclusive)
# Output to TSV
do_test_data() {

  my_id=0   #debug
  get_applicationid                         # set _APPLICATIONID
  get_topicid                               # set _TOPICID

  while IFS=$'\t' read -r col1 col2 col3 ; do
    (( my_id++ ))
    [[ $col1 -lt $_FIRST_ID ]] && { continue ; }
    _SERIAL=$col1
    echo "${_SERIAL}" > debug/${my_id}_SERIAL-$_OUTPUT   #debug
    echo -e "$(LC_ALL=US date) ID=${_SERIAL}" >> HTTP_CODE
    _QUESTION=$( echo "${col2}" | sed 's/"/\\"/g' | tr -d '\r\n' )
    echo "${_QUESTION}" > debug/${my_id}_QUESTION-$_OUTPUT   #debug
    _SQL_ORIG="$( echo -n "${col3}" | tr -d '\r\n' )"
    echo "${_SQL_ORIG}" > debug/${my_id}_SQL_ORIG-$_OUTPUT   #debug
    _SQL_ORIG_SED="$( echo -n "${col3}" | tr -d '\r\n' | sed 's/"/\\"/g' | sed 's/;$//' )"
    echo "${_SQL_ORIG_SED}" > debug/${my_id}_SQL_ORIG_SED-$_OUTPUT   #debug

    get_correlation_id

    post_message                              # set _MSG_BODY and _MSG_BODY_ID

    get_message_details                       # set _MSG_DETAILS, _SQL and _SQL_SED 

    # Get Natural Language answer according to SQL statement

    # Confirmed:
    # _SQL_ORIG_SED
    echo get_nl_result "${_SQL_ORIG_SED}" > debug/${my_id}_NL_RESULT_ORIG-CALL-$_OUTPUT    #debug
    _NL_RESULT_ORIG="$(get_nl_result "${_SQL_ORIG_SED}" NL_RESULT_ORIG)"
    echo "${_NL_RESULT_ORIG}" > debug/${my_id}_NL_RESULT_ORIG-$_OUTPUT    #debug
    # _DATA_ORIG
    _DATA_ORIG="$(echo ${_NL_RESULT_ORIG} | jq -e '.tabular_data.data' | tr -d '\n' | tee DATA_ORIG)"
    _DATA_ORIG_SORTED="$( echo ${_NL_RESULT_ORIG} | jq -e '.tabular_data.data' | jq 'sort' | tee DATA_ORIG_SORTED )"
    echo "${_DATA_ORIG}" > debug/${my_id}_DATA_ORIG-$_OUTPUT    #debug
    echo "${_DATA_ORIG_SORTED}" > debug/${my_id}_DATA_ORIG_SORTED-$_OUTPUT    #debug
    echo -e "_SQL_ORIG_SED $(declare -p _HTTP_CODE)" >> HTTP_CODE

    # Non-confirmed:
    _NL_RESULT2="$(get_nl_result2 NL_RESULT)"
    echo "${_NL_RESULT2}" > debug/${my_id}_NL_RESULT2-$_OUTPUT    #debug
    # _SQL_SED
    _SQL="$(jq '.sql_result' <<<"${_NL_RESULT2}" )"
    _SQL_SED="$(jq '.sql_result' <<<"${_NL_RESULT2}" )"
    # _DATA
    _DATA="$( jq -e '.tabular_data.data' <<<"${_NL_RESULT2}" | tr '\r\n' '  ' | tr -s ' ' )"
    _DATA_SORTED="$( jq 'sort' <<<"${_DATA}" | tee DATA_SORTED )"
    echo "${_DATA}" > debug/${my_id}_DATA-$_OUTPUT    #debug
    echo "${_DATA_SORTED}" > debug/${my_id}_DATA_SORTED-$_OUTPUT    #debug
    # Natural language result
    _NLP_RESULT2=$( jq '.nl_result' <<<"${_NL_RESULT2}" | sed -E 's/<[^>]*>//g ; s/[[:space:]]+/ /g' | tr '\n\r' '  ' | tr -s ' ' | tr -d '\\n' )
    echo "${_NLP_RESULT2}" > debug/${my_id}_NLP_RESULT2-$_OUTPUT    #debug

#   # _SQL_SED
#   echo get_nl_result "${_SQL_SED}" > debug/${my_id}_NL_RESULT-CALL-$_OUTPUT    #debug
#   _NL_RESULT="$(get_nl_result "${_SQL_SED}" NL_RESULT)"
#   echo "${_NL_RESULT}" > debug/${my_id}_NL_RESULT-$_OUTPUT   #debug

#   # _DATA
#   _DATA="$( echo ${_NL_RESULT} | jq -e '.tabular_data.data' | tr -d '\n' )"
#   _DATA_SORTED="$( echo ${_NL_RESULT} | jq -e '.tabular_data.data' | jq 'sort' | tee DATA_SORTED )"
#   echo "${_DATA}" > debug/${my_id}_DATA-$_OUTPUT   #debug
#   echo "${_DATA_SORTED}" > debug/${my_id}_DATA_SORTED-$_OUTPUT   #debug
#   echo -e "_SQL_SED $(declare -p _HTTP_CODE)" >> HTTP_CODE

    #============================================ COMPARISON
    r1_empty="$(echo -n "${_DATA_ORIG}" | tr -d '[] \n\r')"
    r2_empty="$(echo -n "${_DATA}" | tr -d '[] \n\r')"


    #================
    #================
    #= PRINT REPORT =
    #================
    #================

    #--------------- DATE
    echo -ne "$(date '+%Y/%m/%d')\t"
    #--------------- QUESTION ID
    echo -ne "${_SERIAL}\t"
    #--------------- QUESTION
    echo -ne "${col2}\t"
    #--------------- SQL_ORIG
    echo -ne "${_SQL_ORIG}\t"
    #--------------- DATA_ORIG
    if [[ $(echo ${_DATA_ORIG} | wc -c) -gt 49999 ]] ; then
      echo -ne "FIELD TOO LARGE\t"
    else
      echo -ne ${_DATA_ORIG}"\t"
    fi
    #--------------- NL_RESULT_ORIG: Natural language result (Verbal eRAG answer)
    echo -ne "$(jq '.nl_result' < debug/${my_id}_NL_RESULT_ORIG_CURL_RESPONSE-$_OUTPUT | sed -E 's/<[^>]*>//g ; s/[[:space:]]+/ /g')\t" | tr '\n\r' '  ' | tr -s ' '

    #--------------- SQL
    echo -ne "$(echo -en "${_SQL}"  | tr '\n' ' ')\t"

    #--------------- DATA
    if [[ $(echo ${_DATA} | wc -c) -gt 49999 ]] ; then
      echo -ne "FIELD TOO LARGE\t"
    else
      echo -ne ${_DATA}"\t"
    fi

    #--------------- NL_RESULT: Natural language result (Verbal eRAG answer)
    #echo -ne "$(jq '.nl_result' < debug/${my_id}_NL_RESULT_CURL_RESPONSE-$_OUTPUT | sed -E 's/<[^>]*>//g ; s/[[:space:]]+/ /g')\t" | tr '\n\r' '  ' | tr -s ' '
    echo -ne "${_NLP_RESULT2}\t"


    #--------------- COMPARISON: same/different
#   if [[ -z $r1_empty && -z $r2_empty ]] ; then 
#     echo -ne "same\t"
#   else
#     [[ "$(echo -n "${_DATA_ORIG}" | md5sum)" == "$(echo -n "${_DATA}" | md5sum)" ]] && echo -ne "same\t" || echo -ne "different\t"   
#   fi
    if [[ "$(echo -n "${_DATA_ORIG_SORTED}" | md5sum)" == "$(echo -n "${_DATA_SORTED}" | md5sum)" ]] ; then
      echo -ne "same\t"
    else
      echo -ne "different\t"
    fi
    #echo -n "${_DATA_ORIG_SORTED}" | md5sum > debug/${my_id}_DATA_ORIG_SORTED_md5-$_OUTPUT    #debug
    #echo -n "${_DATA_ORIG_SORTED}" > debug/${my_id}_DATA_ORIG_SORTED_echo-$_OUTPUT    #debug
    #echo -n "${_DATA_SORTED}" | md5sum > debug/${my_id}_DATA_SORTED_md5-$_OUTPUT    #debug
    #echo -n "${_DATA_SORTED}" > debug/${my_id}_DATA_SORTED_echo-$_OUTPUT    #debug

    #--------------- SIMILARITY: 0-100%
    do_similarity

    [[ $_SERIAL -ge $_LAST_ID ]] && { break ; }
    [[ -n $_SLEEP ]] && sleep $_SLEEP
  done < "${_ACCURACY_FILE}" | tr -d '\r' | tee /tmp/erag-out-$_OUTPUT
  
  delete_topic   #debug

}

function do_similarity() {
python3 << EOF
import sys
from difflib import SequenceMatcher

# Load the raw HTML from r1
with open('DATA_ORIG_SORTED', 'r', encoding='utf-8') as f:
    html_1 = f.read()

# Load the raw HTML from r2
with open('DATA_SORTED', 'r', encoding='utf-8') as f:
    html_2 = f.read()

# Compare the two HTML strings with difflib
matcher = SequenceMatcher(None, html_1, html_2)
similarity_ratio = matcher.ratio()  # returns a value between 0 and 1

similarity_percentage = similarity_ratio * 100
#print(f"Similarity: {similarity_percentage:.2f}%")
print(f"{similarity_percentage:.2f}%")

EOF
}

# Debug options
#   -g1               Get Application ID  - Run: get_applicationid
#   -g2               Get Topic ID        - Run: get_applicationid get_topicid
#   -g3               Get Message ID      - Run: get_applicationid get_topicid post_message
#   -g4               Get SQL             - Run: get_applicationid get_topicid post_message get_message_details

function usage() {

  cat << EOF

  NAME

    $(basename $0) – Test accurracy of goldenset

  USAGE:

    $(basename $0) [<options>]

  OPTIONS:

    -t                Test accuracy of goldenset file
    -file <filename>  Give name of accurracy file to use. Defaults to use file "accuracy.tsv" in current directory.
    -tok <value>      Set TOKEN
    -api <name>       Set API. Supported: tempo2, goldenset
    -f <id num>       Set FIRST ID to process. Default is whole accurracy file.
    -l <id num>       Set LAST ID to process. Default is whole accurracy file.
    -s <seconds>      Set sleep value between each line test. Defautl none.
    -getids           DISPLAY ALL TOPIC IDS (specify as last argument in cli)
    -deleteids        DELETE ALL TOPIC IDS (specify as last argument in cli)
    -h                Help - Display usage

  DEFAULT

    $(basename $0) -h

  EXAMPLES:

   $(basename $0) -file tempo2.tsv -t     # Specify file to test
   $(basename $0) -f 1 -l 1 -t            # Test only ID=1
   $(basename $0) -api tempo2             # Change API's "eRAG experimental app" and "FastAPI" to tempo2
   $(basename $0) -tok '...'              # Specify token
   $(basename $0) -f 1 -l 5 -api tempo2 -tok '...' -file tempo2.tsv -t    # Run queries found between 1-5
   $(basename $0) -api goldenset -tok '...' -file goldenset.tsv -t        # Run all queries

EOF
exit

}

function do_menu() {

check_python_venv
while [[ $# -ne 0 ]] ; do

  case $1 in
    "-g1") 
        get_applicationid
        #echo _HTTP_CODE="${_HTTP_CODE["get_applicationid"]}"
        #echo _APPLICATIONID="${_APPLICATIONID}"
        ;;
    "-g2") 
        get_applicationid
        get_topicid
        #echo _TOPICID=$_TOPICID
        ;;
    "-g3") 
        echo "running get_applicationid" ; get_applicationid
        echo _APPLICATIONID=$_APPLICATIONID
        echo "running get_topicid" ; get_topicid
        echo _TOPICID=$_TOPICID
        echo "running post_message" ; post_message
        echo _MSG_BODY_ID=$_MSG_BODY_ID
        ;;
    "-g4") 
        echo -e "\n----------running get_applicationid\n" ; get_applicationid
        echo -e _APPLICATIONID=$_APPLICATIONID
        echo -e "\n----------running get_topicid\n" ; get_topicid
        echo -e _TOPICID=$_TOPICID               # $(LC_ALL=US date) >> topic-msg
        echo -e "\n----------running post_message\n" ; post_message
        echo -e _MSG_BODY_ID=$_MSG_BODY_ID       # $(LC_ALL=US date) >> topic-msg
        echo -e "\n----------running get_message_details\n" ; get_message_details
        echo -e "\n_MSG_DETAILS=${_MSG_DETAILS}\n"
        echo -e "\n_SQL=${_SQL}\n"
        echo -e "\n----------running delete_topic\n" ; delete_topic
        exit
        ;;
    "-t") 
        do_test_data
        ;;
    "-f") 
        shift ; _FIRST_ID=$1
        ;;
    "-getids") 
        get_all_topicids ; echo $_TOPIC_IDS ; exit
        ;;
    "-deleteids") 
        delete_all_topicids ; exit
        ;;
    "-file") 
        shift ; [[ ! -s $1 ]] && { echo -e "\nAccuracy file not given, is empty or does not exist.\n" ; exit 1 ; } || _ACCURACY_FILE=$1
        ;;
    "-l") 
        shift ; _LAST_ID=$1
        ;;
    "-s") 
        shift ; _SLEEP=$1
        ;;
    "-tok"|"-token") 
        shift ; _TOK="Authorization: Token ${1}"
        ;;
    "-api") 
        shift
        FastAPI="https://${1}.ws-euc1.gigaspaces.net/api/data-lab"
        eRAG_experimental_app="https://${1}.ws-euc1.gigaspaces.net/api/erag-backend"
        #FastAPI="https://tenant-${1}.erag-c1.gigaspaces.net/api/data-lab"
        #eRAG_experimental_app="https://tenant-${1}.erag-c1.gigaspaces.net/api/erag-backend"
        _OUTPUT="${1}"
        ;;
    "-h") 
        usage
        ;;
    *) echo -e "\nOption \"${1}\" is unknown.\n" ; exit 1 
       ;;
  esac
  shift

done

}

########## MAIN ##########

requirements "${@}"
do_env
do_menu "${@}"
#do_test_data

