#!/usr/bin/env bash
#/opt/homebrew/bin/bash - new bash v5

# Check requirements

function requirements() {
[[ $# -eq 0 || $1 == "-h" ]] && usage
python3 --version >/dev/null 2>&1 || { echo -e "\nInstall python3\n" ; exit 1 ; }
[[ ! "$(basename $(pwd))" == "erag" ]] && { echo -e "\nRun script inside folder named \"erag\"\n" ; exit 1 ; }
#cd ; cd erag || { echo "\nCreate erag directory\n" ; exit 1 ; }
# e.g. token file contents: "Authorization: Token -Wi..."
#[[ ! -s token ]] && { echo "\nPut token in file erag/token\n" ; exit 1 ; }
#[[ ! -s accuracy.tsv ]] && { echo "\nImport file erag/accuracy.tsv\n" ; exit 1 ; }
if [[ "$(echo "${@}" | grep -o -- '-file')" != "-file" && ! -s accuracy.tsv ]] ; then
  echo ; [[ "$(echo "${@}" | grep -o -- '-file')" != "-file" ]] && echo -e "The \"-file\" argument is missing."
  [[ ! -s accuracy.tsv ]] && echo -e "The file \"accuracy.tsv\" is missing or empty."
  echo ; exit 1
fi
}

# ENVIRONMENT

function do_env() {
# goldenset API
# FastAPI='https://tenant-goldenset.erag-c1.gigaspaces.net/api/data-lab'
# eRAG_experimental_app='https://tenant-goldenset.erag-c1.gigaspaces.net/api/erag-backend'
# tempo2 API
# https://tenant-tempo2.erag-c1.gigaspaces.net/api/data-lab/docs
# https://tenant-tempo2.erag-c1.gigaspaces.net/api/erag-backend/docs
FastAPI=""
eRAG_experimental_app=""
_OUTPUT=""
_ACCURACY_FILE="accuracy.tsv"
_CURL_RESPONSE="/tmp/erag_curl_response"
declare -g -A _EXIT_CODE
declare -g -A _HTTP_CODE
# goldenset token - Authorization: Token -WiA1-MmPjMG_BHxyo$8Ndze5uz4@CQ1BgRbcVtPMo
# tempo2 token - Authorization: Token 7K@htaemdlptf7R_$@1VjZ8USukKj@hwyuikAUFQE5
_TOK='Authorization: Token 7K@htaemdlptf7R_$@1VjZ8USukKj@hwyuikAUFQE5'
_APPLICATIONID=""
_USERID=1
_TOPICID=""
_MSG_BODY=""
_MSG_BODY_ID=""
_ASSISTANT_MSG=""                 # Verbal eRAG answer
_SQL=""                           # New SQL statement
_SQL_SED=""                       # New SQL statement - escaping double quotes are escaped: \"
_SQL_ORIG=""                      # Original SQL statement
_SQL_ORIG_SED=""                  # Original SQL statement - double quotes are escaped: \"
_MSG_DETAILS=""
_NL_RESULT=""                     # Get Natural Language answer to SQL
_NL_RESULT_ORIG=""                # Get Natural Language answer to SQL_ORIG
_FIRST_ID=1
_LAST_ID=50
LC_ALL=US date '+%Y-%m-%d %H:%M:%S' >> HTTP_CODE        # Hold http codes for current run
LC_ALL=US date '+%Y-%m-%d %H:%M:%S' > GET_NL_RESULT
# Variables for report
_SERIAL=""                        # Question ID
_QUESTION=""                      # Question asked - double quotes are escaped: \"
_RESULT=""                        # Current Query result
_RESULT_ORIG=""                   # Confirmed Query result
_SLEEP=""
_ERR_LOG=/tmp/erag-error.log
_ERR_LOG_TMP=/tmp/erag-error-tmp.log
}

check_python_venv() {

#python3 -m venv myvenv
#source myvenv/bin/activate
#pip install beautifulsoup4

# Define the virtual environment path
VENV_PATH="myvenv"
# Step 1: Check if the virtual environment exists
if [ ! -d "$VENV_PATH" ]; then
    #echo "Virtual environment not found. Creating one..."
    python3 -m venv "$VENV_PATH" || { echo "Failed to create virtual environment"; exit 1; }
fi
# Step 2: Activate the virtual environment
source "$VENV_PATH/bin/activate" || { echo "Failed to activate virtual environment"; exit 1; }
# Step 3: Check if beautifulsoup4 is installed
if ! pip show beautifulsoup4 > /dev/null 2>&1; then
    #echo "BeautifulSoup4 is not installed. Installing it now..."
    pip install beautifulsoup4 || { echo "Failed to install BeautifulSoup4"; exit 1; }
fi
}

# FUNCTIONS

# GET 1 - Get application id - eRAG experimental app/Get All Applications
##  'https://tenant-goldenset.erag-c1.gigaspaces.net/api/erag-backend/v1/applications' \
function get_applicationid() {
  _HTTP_CODE["${FUNCNAME[0]}"]=$( curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'GET' \
  "${eRAG_experimental_app}/v1/applications" \
  -H 'accept: application/json' \
  -H "${_TOK}")
  #cat ${_CURL_RESPONSE}
  #_HTTP_CODE["${FUNCNAME[0]}"]="${_APPLICATIONID}"
  _APPLICATIONID="$( jq -e '.[].applicationId' < ${_CURL_RESPONSE} 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_applicationid " ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  #echo _APPLICATIONID=$_APPLICATIONID
}

# GET 2 - Get topic id - FastAPI/get all topics for this app for this user
function get_topicid() {
  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'GET' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}")
  _TOPICID="$(jq -e '.[].id' < ${_CURL_RESPONSE} 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_topicid _TOPICID" ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  #declare -p _HTTP_CODE
  #echo _TOPICID="${_TOPICID}"
}

# GET 3 - Get message body id - FastAPI/Submit a new question to the topic
function post_message() {
  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'POST' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics/${_TOPICID}/messages" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}" \
  -H 'Content-Type: application/json' \
  -d '{ "message": "'"${_QUESTION}"'" }')
  _MSG_BODY=$(<${_CURL_RESPONSE})
  #_MSG_BODY_ID="$(echo "${_MSG_BODY}" | jq -e '.[] | select(.role == "assistant") | .id')"
  # jq -er '...' <<< "$myvar"                    # Using a here-string
  # jq -er '.name' < <(echo "$myvar")            # Using process substitution
  _MSG_BODY_ID="$( jq -e '.[] | select(.role == "assistant") | .id' <<< "${_MSG_BODY}" 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_topicid _MSG_BODY_ID" "$(<${_ERR_LOG_TMP})" ; } >> $_ERR_LOG
  #_ASSISTANT_MSG="$(echo "${_MSG_BODY}" | jq -e '.[] | select(.role == "assistant") | .message')"
  _ASSISTANT_MSG="$( jq -e '.[] | select(.role == "assistant") | .message' <<< "${_MSG_BODY}" 2> $_ERR_LOG_TMP )"
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_topicid _ASSISTANT_MSG" ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  #echo _MSG_BODY="${_MSG_BODY}"
  #echo _MSG_BODY_ID="${_MSG_BODY_ID}"
  #declare -p _HTTP_CODE
}

# GET 4 - Use message_id to get sql "Current SQL statement - generated" - FastAPI/Get message details
function get_message_details() {
  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'GET' \
  "${FastAPI}/v1/applications/${_APPLICATIONID}/data-lab/topics/${_TOPICID}/messages/${_MSG_BODY_ID}" \
  -H 'accept: application/json' \
  -H "user-id: ${_USERID}" \
  -H "${_TOK}")
  _MSG_DETAILS=$(<${_CURL_RESPONSE})
  #_SQL=$(echo "${_MSG_DETAILS}" | jq -er '.sql')
  _SQL=$( jq -er '.sql' <<< "${_MSG_DETAILS}" 2> $_ERR_LOG_TMP )
  [[ $? -ne 0 ]] && { printf "%s\n" "$(date '+%Y-%m-%d %H:%M:%S') $_SERIAL get_message_details _SQL" ; cat $_ERR_LOG_TMP ; } >> $_ERR_LOG
  _SQL_SED=$(echo "${_SQL}" | sed 's/"/\\"/g')
  declare -p _HTTP_CODE >> HTTP_CODE
  #echo _MSG_DETAILS="${_MSG_DETAILS}"
  #echo _SQL="${_SQL}"
  #echo _SQL_SED="${_SQL_SED}"
}

# Use sql/sql_orig to get "data" and "nl_result" - eRAG experimental app - Sql Nlp Query
# $1 - sql statement
get_nl_result() {
  local run_sql="$(echo -n "${1}" | tr -d '\n\r')"
  _HTTP_CODE["${FUNCNAME[0]}"]=$(curl -s -o $_CURL_RESPONSE -w "%{http_code}" -X 'POST' \
  "${eRAG_experimental_app}/v1/toucan-sql/sql-nlp-query" \
  -H 'accept: application/json' \
  -H "${_TOK}" \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "",
  "sql": "'"${run_sql}"'",
  "model": "azure-openai-gpt4o-2024-08-06",
  "applicationId": "'"${_APPLICATIONID}"'"
  }'
  )           # End of curl subprocess
  echo -e "\n$(LC_ALL=US date '+%Y-%m-%d %H:%M:%S')" >> GET_NL_RESULT
  cat ${_CURL_RESPONSE} | tee -a GET_NL_RESULT
}

###################################
# Compare original sql with new sql
# col1 = Serial
# col2 = Question
# col3 = Query
# Date, question ID, question, Confirmed query, Current query, comparison results (correct, not correct, inconclusive)
# Output to TSV
do_test_data() {
  while IFS=$'\t' read -r col1 col2 col3 ; do
    [[ $col1 -lt $_FIRST_ID ]] && { continue ; }
    _SERIAL=$col1
    echo -e "$(LC_ALL=US date) ID=${_SERIAL}" >> HTTP_CODE
    _QUESTION=$(echo "${col2}" | sed 's/"/\\"/g')
    _SQL_ORIG="$(echo -n "${col3}" | tr -d '\r\n')"
    _SQL_ORIG_SED="$(echo ${col3} | sed 's/"/\\"/g')"

    get_applicationid                         # set _APPLICATIONID
    get_topicid                               # set _TOPICID
    echo "${_QUESTION}" > QUESTION
    post_message                              # set _MSG_BODY and _MSG_BODY_ID

    #echo -e "\n $_SERIAL \n"
    #echo -e "\n _MSG_BODY=$_MSG_BODY\n"
    #echo -e "\n _MSG_BODY_ID=$_MSG_BODY_ID\n"
    get_message_details                       # set _MSG_DETAILS, _SQL and _SQL_SED 
    #echo -e "\n${_MSG_DETAILS}\n"
    #echo -e "\n_SQL_SED=${_SQL_SED}\n"
    #echo -e "\n_SQL_ORIG_SED=${_SQL_ORIG_SED}\n"

    # Get Natural Language answer according to SQL statement
    # _SQL_ORIG_SED
    echo "${_SQL_ORIG_SED}" > SQL_ORIG_SED
    _NL_RESULT_ORIG="$(get_nl_result "${_SQL_ORIG_SED}")"
    echo "${_NL_RESULT_ORIG}" > NL_RESULT_ORIG
    _DATA_ORIG="$(echo ${_NL_RESULT_ORIG} | jq -e '.tabular_data.data' | tr -d '\n' | tee DATA_ORIG)"
    echo -e "_SQL_ORIG_SED $(declare -p _HTTP_CODE)" >> HTTP_CODE
    # _SQL_SED
    echo "${_SQL_SED}" > SQL_SED
    _NL_RESULT="$(get_nl_result "${_SQL_SED}")"
    echo "${_NL_RESULT}" > NL_RESULT
    _DATA="$(echo ${_NL_RESULT} | jq -e '.tabular_data.data' | tr -d '\n' | tee DATA)"
    echo -e "_SQL_SED $(declare -p _HTTP_CODE)" >> HTTP_CODE

    #============================================ COMPARISON
    r1_empty="$(echo -n "${_DATA_ORIG}" | tr -d '[] \n')"
    r2_empty="$(echo -n "${_DATA}" | tr -d '[] \n')"


    #================
    #================
    #= PRINT REPORT =
    #================
    #================

    #--------------- DATE
    echo -ne "$(date '+%Y/%m/%d')\t"
    #--------------- QUESTION ID
    echo -ne "${_SERIAL}\t"
    #--------------- QUESTION
    echo -ne "${col2}\t"
    #--------------- SQL_ORIG
    echo -ne "${_SQL_ORIG}\t"
    #--------------- DATA_ORIG
    if [[ $(echo ${_DATA_ORIG} | wc -c) -gt 49999 ]] ; then
      echo -ne "FIELD TOO LARGE\t"
    else
      echo -ne ${_DATA_ORIG}"\t"
    fi
    #echo -ne "${_ERAG_ORIG_ANSWER}\t"
    #--------------- SQL
    echo -ne "$(echo -en "${_SQL}"  | tr '\n' ' ')\t"
    #echo -ne "${_SQL}\t"
    #--------------- DATA
    if [[ $(echo ${_DATA} | wc -c) -gt 49999 ]] ; then
      echo -ne "FIELD TOO LARGE\t"
    else
      echo -ne ${_DATA}"\t"
    fi
    #echo -ne "${_ERAG_ANSWER}\t"
    #--------------- ASSISTANT_MSG
    echo -ne "$(echo -en "${_ASSISTANT_MSG}" | tr '\n' ' ' | sed -E 's/<[^>]*>//g; s/[[:space:]]+/ /g')\t"
    #--------------- COMPARISON
    if [[ -z $r1_empty && -z $r2_empty ]] ; then 
      echo -ne "same\t"
    else
      [[ "$(echo -n "${_DATA_ORIG}" | md5sum)" == "$(echo -n "${_DATA}" | md5sum)" ]] && echo -ne "same\t" || echo -ne "different\t"   
    fi
    #--------------- SIMILARITY in percentage 0-100%
    do_similarity


    [[ $_SERIAL -ge $_LAST_ID ]] && { break ; }
    [[ -n $_SLEEP ]] && sleep $_SLEEP
  done < <(cat $_ACCURACY_FILE ) | tee /tmp/erag-out-$_OUTPUT
#  pbcopy < /tmp/erag-out-$_OUTPUT
#  echo -e "\n Results copied to clipboard.\n"
}

function do_similarity() {
python3 << EOF
import sys
from difflib import SequenceMatcher

# Load the raw HTML from r1
with open('DATA_ORIG', 'r', encoding='utf-8') as f:
    html_1 = f.read()

# Load the raw HTML from r2
with open('DATA', 'r', encoding='utf-8') as f:
    html_2 = f.read()

# Compare the two HTML strings with difflib
matcher = SequenceMatcher(None, html_1, html_2)
similarity_ratio = matcher.ratio()  # returns a value between 0 and 1

similarity_percentage = similarity_ratio * 100
#print(f"Similarity: {similarity_percentage:.2f}%")
print(f"{similarity_percentage:.2f}%")
EOF
}

# Debug options
#   -g1               Get Application ID  - Run: get_applicationid
#   -g2               Get Topic ID        - Run: get_applicationid get_topicid
#   -g3               Get Message ID      - Run: get_applicationid get_topicid post_message
#   -g4               Get SQL             - Run: get_applicationid get_topicid post_message get_message_details

function usage() {

  cat << EOF

  USAGE:

    $(basename $0) [<options>]

  OPTIONS:

    -t                Test accuracy file
    -file <filename>  Give name of accurracy file to use. Default: use file "accuracy.tsv" in current directory.
    -tok <value>      Set TOKEN
    -api <name>       Set API
    -f                Set FIRST ID to process
    -l                Set LAST ID to process
    -s                Set sleep value between each line test
    -h                Help - Display usage

  DEFAULT

    -h

  ACTIONS:

  EXAMPLES:

   $(basename $0) -file tempo2.tsv -t     Specify file to test
   $(basename $0) -f 1 -l 1 -t            Test only ID=1
   $(basename $0) -api tempo2             Change API's "eRAG experimental app" and "FastAPI" to tempo2
   $(basename $0) -tok '9K@hTAEmdlpTF7r_$@1VjZ8UsUKkJ@HWYuikAUFQE5'       
   $(basename $0) -f 1 -l 1 -api tempo2 -tok '9K@hTAEmdlpTF7r_$@1VjZ8UsUKkJ@HWYuikAUFQE5' -file tempo2.tsv -t

EOF
exit

}

function do_menu() {

check_python_venv
while [[ $# -ne 0 ]] ; do

  case $1 in
    "-g1") 
        get_applicationid
        #echo _HTTP_CODE="${_HTTP_CODE["get_applicationid"]}"
        #echo _APPLICATIONID="${_APPLICATIONID}"
        ;;
    "-g2") 
        get_applicationid
        get_topicid
        #echo _TOPICID=$_TOPICID
        ;;
    "-g3") 
        echo "running get_applicationid" ; get_applicationid
        echo _APPLICATIONID=$_APPLICATIONID
        echo "running get_topicid" ; get_topicid
        echo _TOPICID=$_TOPICID
        echo "running post_message" ; post_message
        echo _MSG_BODY_ID=$_MSG_BODY_ID
        ;;
    "-g4") 
        echo -e "\n----------running get_applicationid\n" ; get_applicationid
        echo -e _APPLICATIONID=$_APPLICATIONID
        echo -e "\n----------running get_topicid\n" ; get_topicid
        echo -e _TOPICID=$_TOPICID               # $(LC_ALL=US date) >> topic-msg
        echo -e "\n----------running post_message\n" ; post_message
        echo -e _MSG_BODY_ID=$_MSG_BODY_ID       # $(LC_ALL=US date) >> topic-msg
        echo -e "\n----------running get_message_details\n" ; get_message_details
        echo -e "\n_MSG_DETAILS=${_MSG_DETAILS}\n"
        echo -e "\n_SQL=${_SQL}\n"
        echo -e "${_ASSISTANT_MSG}" | tr '\n' ' ' | sed -E 's/<[^>]*>//g; s/[[:space:]]+/ /g'
        ;;
    "-t") 
        do_test_data
        ;;
    "-f") 
        shift ; _FIRST_ID=$1
        ;;
    "-file") 
        shift ; [[ ! -s $1 ]] && { echo -e "\nAccuracy file not given, is empty or does not exist.\n" ; exit 1 ; } || _ACCURACY_FILE=$1
        ;;
    "-l") 
        shift ; _LAST_ID=$1
        ;;
    "-s") 
        shift ; _SLEEP=$1
        ;;
    "-tok"|"-token") 
        shift ; _TOK="Authorization: Token ${1}"
        ;;
    "-api") 
        shift
        FastAPI="https://tenant-${1}.erag-c1.gigaspaces.net/api/data-lab"
        eRAG_experimental_app="https://tenant-${1}.erag-c1.gigaspaces.net/api/erag-backend"
        _OUTPUT="${1}"
        ;;
    "-h") 
        usage
        ;;
    *) echo -e "\nOption \"${1}\" is unknown.\n" ; exit 1 
       ;;
  esac
  shift

done

}

########## MAIN ##########

requirements "${@}"
do_env
do_menu "${@}"

