{
 "title": "Main dashboard",
 "description": "v0.2",
 "tags": [ "Master" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "   <a href=\"/d/tJWLBOR7z/main-dashboard?orgId=1&refresh=5s&kiosk\">\n         <div>\n         <img alt=\"TAU Spaceboard\" src=\"/public/img/HEB_bold.jpg\"\n         width=150\">\n         <span style=\"font-size:150%; font-weight:bold ;color:darkblue; padding-left:10px; font-style:italic\"> SpaceBoard </span>\n         </div>\n      </a>\n   "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spaces list",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "space_active" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "space_data_data-types",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "space_active", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "NB - Application",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "query": "SELECT max(\"active_code\") FROM \"systemd_units\" WHERE (\"nb_role\" = 'application'  AND (\"name\" = 'nginx.service' OR \"name\" = 'consul-template.service' OR \"name\" = 'consul.service')) AND $timeFilter GROUP BY time($interval), \"host\" fill(none) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "nginx.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul-template.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul.service" }
     ]
    }
   ]
  },
  {
   "title": "NB - Management",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "query": "SELECT max(\"active_code\") FROM \"systemd_units\" WHERE ((\"nb_role\" = 'management' ) AND \"name\" = 'nginx.service' ) AND $timeFilter GROUP BY time($interval), \"host\" fill(none) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "nginx.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul-template.service" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "consul.service" }
     ]
    }
   ]
  },
  {
   "title": "Micro Services",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pu_ServiceRoute_service-latency",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Services - Total Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT SUM(val) FROM (SELECT last(value) as val FROM \"jvm_memory_heap_used-bytes\" WHERE $timeFilter AND pu_name != '' GROUP BY \"pu_instance_id\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "!=", "value": "data-feeder-spaceB" }
     ]
    }
   ]
  },
  {
   "title": "Memory Used/Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_pu_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pu_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvm_memory_heap_used-bytes",
     "query": "SELECT sum(\"value\") FROM \"jvm_memory_heap_used-bytes\" WHERE  pu_name != '' AND $timeFilter GROUP BY time($__interval), \"pu_name\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pu_name", "operator": "!=", "value": "data-feeder-spaceB" }
     ]
    }
   ]
  },
  {
   "title": "Object Type Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_space_name : $tag_data_type_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "data_type_short_name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "space_data_data-types",
     "query": "SELECT SUM(val) FROM (select last(value) as val FROM \"space_data_tiered-storage-disk-entries\" WHERE  data_type_name != 'java.lang.Object' AND $timeFilter AND space_active = 'true' GROUP BY space_name,data_type_name, pu_instance_id) GROUP BY data_type_name, space_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "data_type_name", "operator": "!=", "value": "java.lang.Object" },
      { "condition": "AND", "key": "data_type_short_name", "operator": "!=", "value": "Value" }
     ]
    }
   ]
  },
  {
   "title": "Grid CPU %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_cpu_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Grid Memory %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os_memory_used-percent",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Northbound CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"os_cpu_used-percent\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "OR", "key": "nb_role", "operator": "=", "value": "management" }
     ]
    }
   ]
  },
  {
   "title": "Northbound Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"nb_role\" = 'application') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "nb_role", "operator": "=", "value": "application" },
      { "condition": "OR", "key": "nb_role", "operator": "=", "value": "management" }
     ]
    }
   ]
  },
  {
   "title": "DI CPU %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"value\") FROM \"os_cpu_used-percent\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gs_service", "operator": "=", "value": "di" }
     ]
    }
   ]
  },
  {
   "title": "DI Memory %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "gs_service", "operator": "=", "value": "di" }
     ]
    }
   ]
  },
  {
   "title": "DI Server Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "alias": "TEst",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "query": "SELECT last(\"DaemonThreadCount\") FROM \"kafka.thread_count\" WHERE $timeFilter GROUP BY time(10s), \"host\" fill(0) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "odsxkafka.service" }
     ]
    },
    {
     "alias": "test123",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "systemd_units",
     "select": [
      [
       { "params": [ "active_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "odsxzookeeper.service" }
     ]
    }
   ]
  }
 ]
}