app.secretKey=f1b4Fy2m6N2icOB5H0myUaA1FaY3fIxO
app.algorithm=AES
app.keySize=256
app.cipherMode=AES/CBC/PKCS5Padding
app.db.path=/home/jay/work/gigaspace/gs-vault/src/main/resources/
app.db.name=vault.db